name: "Build and Test"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: github-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: >
        git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: export NIXPKGS_ALLOW_UNFREE=1 && nix-build -E 'with (import (fetchTarball "https://github.com/goromal/anixpkgs/archive/refs/tags/v0.5.0.tar.gz") {}); ceres-factors.override { pkg-src = lib.cleanSource ./.; }'
